### ISSUE TITLE
Support for remote files via plex-mpv-shim or jellyfin-mpv-shim

### ISSUE THREAD

**Issue by azizLIGHT** [LiTO773/trakt-mpv#1]
I get the error "Unable to Scrobble" for media hosted on Plex or Jellyfin, both tv shows and movies: 

![Screenshot from 2021-03-20 12-07-46](https://user-images.githubusercontent.com/8013867/111876469-4b27a380-8975-11eb-906b-109242c46710.png)
![Screenshot from 2021-03-20 12-21-08](https://user-images.githubusercontent.com/8013867/111876814-dbb2b380-8976-11eb-8d86-153ce61d199e.png)

The script works fine for local files, but more of my media is stored remotely than ever before in places like Plex and Jellyfin servers and I wish I can scrobble files on there to trakt using this script. When I use it with plex-mpv-shim, the log shows: 

```
2021-03-20 12:07:45,182 [   ERROR] mpv: trakt_mpv: Traceback (most recent call last):
2021-03-20 12:07:45,182 [   ERROR] mpv: trakt_mpv: File "/home/aziz/.config/mpv/scripts/trakt-mpv/main.py", line 332, in <module>
2021-03-20 12:07:45,182 [   ERROR] mpv: trakt_mpv: main()
2021-03-20 12:07:45,182 [   ERROR] mpv: trakt_mpv: File "/home/aziz/.config/mpv/scripts/trakt-mpv/main.py", line 326, in main
2021-03-20 12:07:45,182 [   ERROR] mpv: trakt_mpv: switch[sys.argv[1]](sys.argv, data)
2021-03-20 12:07:45,183 [   ERROR] mpv: trakt_mpv: File "/home/aziz/.config/mpv/scripts/trakt-mpv/main.py", line 122, in query
2021-03-20 12:07:45,183 [   ERROR] mpv: trakt_mpv: __query_movie(infos.group(1), infos.group(2), configs)
2021-03-20 12:07:45,183 [   ERROR] mpv: trakt_mpv: File "/home/aziz/.config/mpv/scripts/trakt-mpv/main.py", line 177, in __query_movie
2021-03-20 12:07:45,183 [   ERROR] mpv: trakt_mpv: show_title = res.json()[0]['movie']['title']
2021-03-20 12:07:45,183 [   ERROR] mpv: trakt_mpv: IndexError: list index out of range
```

Maybe trakt-mpv cannot get the media info because the media is coming via Plex via plex-mpv-shim to mpv instead of being stored on a local disk. However, you can see that mpv knows the media info when its shown at the bottom left of the screenshots, above the progress bar

**Comment by LiTO773** [comment]
Uhm I see. I've never used Plex or Jellyfin so I've never experienced that issue.
I'm a bit busy this week so I'm likely not going to be able to fix it this week, but when I get some free time will try to set up a server and replicate the issue.

Thanks for posting it, if anyone else has time to fix it feel free, otherwise I'll try to check it out when I can 🙂

**Comment by azizLIGHT** [comment]
I can invite you to that Plex server where it's already happening for debugging if you want. Share the Plex username  or email address you'd like to use, it can be a temporary account for testing purposes

**Comment by azizLIGHT** [comment]
I changed `mp.get_property('filename')` on line 75 in `trakt-mpv.lua` to be `mp.get_property('media-title')` and now I can scrobble plex/jellyfin hosted files playing in mpv onto trakt. 

The problem was that files served from plex/jellyfin give mangled filenames like `file.mkv?X-Plex-Token=transient-&X-Plex-Version=2_` (checked info by pressing i key inside mpv) and since the script relies on the filename to do lookups, it would fail
![Screenshot from 2021-11-26 11-49-03_](https://user-images.githubusercontent.com/8013867/143613846-bc25cf26-5cc1-40aa-a54e-30e7187e911a.png)

I noticed the title passed to mpv from plex/jellyfin is usually correct, and tried to make use of it for the lookup using media-title. It seems to work okay enough as long as what's passed can be looked up by the script on trakt

I haven't noticed any problems with scrobbling local files with this change yet either
